### ISSUE TITLE
Maybe Regression in 0.8.6 -> Demo ktorFeature broken in version 0.8.6

### ISSUE THREAD

**Issue by frnknglrt** [kwebio/kweb-core#181] opened 2021-03-01 20:25 UTC
**Describe the bug**
Hello,

i just noticed that the version 0.8.6 seems to break the demo ktorFeature. This demo project is working as intended with version 0.8.5 as dependency but it no longer works when using 0.8.6. 

This demo uses an on.click event in combination with KVar. While the on.click event still works, the Kvar is no longer updated in 0.8.6. 

**To Reproduce**
Checkout the demo ktorFeature (https://github.com/kwebio/kweb-demos/tree/master/ktorFeature). 

1. Edit build.gradle and set the kweb version number to 0.8.5. 
2. Run the project and kweb is working as intended
3. Now switch kweb to version 0.8.6. Then the demo is no longer working. When entering any values into the input form and clicking on the "go" button, the headline is not updated anymore, because the KVar is not updated. (I tested it by attaching an observer to the Kvar called `next`

**Expected behavior**
I'd expect the kvar to correctly contain the current value from the input field. This is no longer the case. 

Unfortunately, i'm currently lacking time to revisit the changes made prior to release 0.8.6. So i can't pin down which exact change in 0.8.6 actually caused this bug to appear. However, i'd offer to donate a test case for reproducing this bug.

**Comment by Derek52** [comment] 2021-03-12 18:54
Thanks for pointing this out. I made the changes that caused this bug. I've found the cause of the problem, and am working on the best way to fix it.

**Comment by sanity** [comment] 2021-04-03 17:01
We think #59 will fix this, it will be implemented soon.

**Comment by sanity** [comment] 2021-05-14 00:23
Should be fixed in `0.9.0`.

**Comment by sanity** [comment] 2021-05-18 17:22
Closing, please reopen if this problem persists.

**Closed by sanity** 2021-05-18 17:22 UTC
Labels: bug, regression
